### ISSUE TITLE
Plant list needs better sorting

### ISSUE THREAD

**Issue by zak-schlemmer** [zak-schlemmer/growmobot#20]
It looks like the plant list needs better sorting.
Maybe alphabetical?

**Comment by signalpoint** [comment]
Probably sort by last updated, i.e. the plants you interacted with most recently will stay towards the top of the list.

**Comment by zak-schlemmer** [comment]
I changed this to alphabetical a while back.
I like your idea; but I find that I tend to have multiple similarly named plants from clones that would be updated.
Alphabetical seems best for me, personally, but this might be a good thing to consider making user configurable in the long-term. 
Going to open a new issue for that.
